sudo: required
services:
  - docker

before_install:
  - docker build -t coniix/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true coniix/react-test npm test

after_success:
  - docker build -t coniix/multi-client ./client
  - docker build -t coniix/multi-nginx ./nginx
  - docker build -t coniix/multi-server ./server
  - docker build -t coniix/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to the Docker hub
  - docker push coniix/multi-client
  - docker push coniix/multi-nginx 
  - docker push coniix/multi-server
  - docker push coniix/multi-worker  

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "multi-container"
  env: "Multi-container-env"
  bucked_name: "elasticbeanstalk-eu-north-1-313582925907"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"